# Generated by Django 4.0.5 on 2022-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servings', '0001_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='servings.serving'),
        ),
    ]
