# Generated by Django 4.0.5 on 2022-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0002_rename_serving_food_portion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('foods', models.ManyToManyField(to='foods.food')),
            ],
        ),
    ]
