# Generated by Django 4.0.5 on 2022-06-24 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
