# Generated by Django 4.0.5 on 2022-06-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_rename_serving_food_portion'),
        ('servings', '0002_serving_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serving',
            name='foods',
        ),
        migrations.AddField(
            model_name='serving',
            name='foods',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='foods.food'),
            preserve_default=False,
        ),
    ]
