# Generated by Django 4.0.5 on 2022-06-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servings', '0003_remove_serving_foods_serving_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serving',
            name='name',
        ),
    ]
